# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20150526_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcode',
            name='rate',
            field=models.DecimalField(decimal_places=3, help_text="For a 20% VAT rate, enter '0.200'", max_digits=5),
        ),
        migrations.AlterField(
            model_name='vatcode',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
